server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: catalogRoute
          uri: lb://catalog-service/
          predicates:
            - Path=/api/v1/movies/catalog/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enable: true
    service-url:
      default-zone: http://localhost:8761/
    instance:
      prefer-ip-address: true
